Require analysis of solution
bdetwiler/draft-detecting-unwanted-location-trackers pull request #77
Opened 2023-10-06 15:24 UTC by bledvina

This change is intended to address issue #68

2023-10-06 19:44 UTC, ekr commented
As a note, it would be great to have PR titles that were more clear.

2023-10-06 19:46 UTC, ekr requested changes

2023-10-06 19:46 UTC, ekr commented on charter/charter-detecting-unwanted-location-trackers.md
> +* Produce evidence of efficacy of proposed solution
What would this evidence potentially consist of?

2023-10-06 22:41 UTC, tfpauly requested changes

2023-10-06 22:41 UTC, tfpauly commented on charter/charter-detecting-unwanted-location-trackers.md
> +* Produce evidence of efficacy of proposed solution
I think this doesn't belong as its own milestone. Instead, you'd want to say somewhere that the standards document needs to include a good threat analysis and security analysis before publishing.

2023-10-13 15:49 UTC, zaeddinger approved these changes

2023-10-13 15:51 UTC, zaeddinger approved these changes

2023-10-19 22:44 UTC, tfpauly approved these changes

2023-10-23 23:11 UTC, merged